
docker:image:
  stage: build
  image: docker:1.12
  services:
    - docker:dind
  script:
    - docker version
    - docker-compose -f local/docker-compose.yml up -d
    - docker-compose -f local/docker-compose.yml scale spark_slave=3
    - docker-compose -f local/docker-compose.yml logs --follow
