# start spark_master using /opt/spark/sbin/start-master.sh
# start spark_slave using /opt/spark/sbin/start-slave.sh spark://spark_master:7077
# start spark_util using /opt/spark/bin/spark-submit --class "Pi" --driver-memory 6g --master spark://spark_master:7077 ./jars/calculatepi_2.11-1.0.jar 100

######################################################################################################
####### Need to run a command that keeps container alive after starting master and slaves ############
######################################################################################################

version: '2'
services:
  sparkmaster:
    image: shawks03/sparktitantests
    container_name: sparkmaster
    volumes:
      - ./scripts:/scripts
    command: /scripts/run-master.sh
    ports:
      - 8080:8080
  
  spark_slave:
    image: shawks03/sparktitantests
    command: /scripts/run-slave.sh
    depends_on:
      - sparkmaster
    volumes:
      - ./scripts:/scripts
  
  spark_util:
    image: shawks03/sparktitantests
    container_name: spark_util
    command: /scripts/run-submitter.sh
    volumes:
      - ./scripts:/scripts
    depends_on:
      - spark_slave

#  titan:
#    image: shawks03/sparktitantests
#    container_name: titan
#    command: /scripts/start.sh
#    volumes:
#      - ./:/scripts
#    ports:
#      # Elasticsearch
#      - 9300:9300
#      # Gremlin-Server
#      - 8182:8182
