
version: '2'
services:
  sparkmaster:
    build: ./
    image: sparktest
    container_name: sparkmaster
    command: /scripts/run-master.sh
    ports:
      - 8080:8080
  
  spark_slave:
    build: ./
    image: sparktest
    command: /scripts/run-slave.sh
    ports:
      - 4040
      - 8081
    depends_on:
      - sparkmaster
  
  spark_util:
    build: ./
    image: sparktest
    container_name: spark_util
    command: /scripts/run-submitter.sh
    depends_on:
      - spark_slave

#  titan:
#    image: shawks03/sparktitantests
#    container_name: titan
#    command: /scripts/run-titan.sh
#    volumes:
#      - ./scripts:/scripts